q#name: Deploy Frontend (Vercel)
#
#on:
#  push:
#    paths:
#      - frontend/**
#    branches: [main, develop]
#
#  pull_request:
#    types: [opened, synchronize, reopened]
#
#jobs:
#  deploy:
#    runs-on: ubuntu-latest
#    if: "!contains(github.event.head_commit.message, '[skip ci]')"
#    env:
#      IS_MAIN_BRANCH: ${{ github.ref == 'refs/heads/main' }}
#      IS_DEVELOP_BRANCH: ${{ github.ref == 'refs/heads/develop' }}
#      IS_PR: ${{ github.event_name == 'pull_request' }}
#
#    steps:
#      - name: Checkout
#        uses: actions/checkout@v3
#
#      - name: Debug Print
#        run: |
#          echo "IS_MAIN_BRANCH: ${{ env.IS_MAIN_BRANCH }}"
#          echo "IS_DEVELOP_BRANCH: ${{ env.IS_DEVELOP_BRANCH }}"
#          echo "IS_PR: ${{ env.IS_PR }}"
#          echo "GITHUB_REF: ${{ github.ref }}"
#          echo "VERCEL_ORG_ID: ${{ secrets.VERCEL_ORG_ID }}"
#          echo "VERCEL_PROJECT_ID: ${{ secrets.VERCEL_PROJECT_ID }}"
#          echo "PRODUCTION: ${{ env.IS_MAIN_BRANCH }}"
#          echo "GITHUB_DEPLOYMENT_ENV: ${{ env.IS_MAIN_BRANCH && 'Production' || env.IS_DEVELOP_BRANCH && 'Staging' || 'Preview' }}"
#
#
#      - name: Deploy to Vercel Action
#        uses: BetaHuhn/deploy-to-vercel-action@v1
#        with:
#          GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
#          VERCEL_TOKEN: ${{ secrets.VERCEL_TOKEN }}
#          VERCEL_ORG_ID: ${{ secrets.VERCEL_ORG_ID }}
#          VERCEL_PROJECT_ID: ${{ secrets.VERCEL_PROJECT_ID }}
#          VERCEL_SCOPE: ${{ secrets.VERCEL_SCOPE }}
#          PRODUCTION: ${{ env.IS_MAIN_BRANCH }}
#          GITHUB_DEPLOYMENT_ENV: ${{ env.IS_MAIN_BRANCH && 'Production' || env.IS_DEVELOP_BRANCH && 'Staging' || 'Preview' }}
#          WORKING_DIRECTORY: frontend/
#      - name: PR Comment
#        uses: phulsechinmay/rewritable-pr-comment@v0.3.0
#        if: ${{ steps.vercel-deploy.outputs.DEPLOYMENT_CREATED && env.IS_PR }}
#        with:
#          message: |
#            This pull request has been deployed to Vercel.
#
#            <table>
#              <tr>
#                <td><strong>✅ Preview:</strong></td>
#                <td><a href='${{ steps.vercel-deploy.outputs.PREVIEW_URL }}'>${{ steps.vercel-deploy.outputs.PREVIEW_URL }}</a></td>
#              </tr>
#              <tr>
#                <td><strong>🔍 Inspect:</strong></td>
#                <td><a href='${ steps.vercel-deploy.outputs.DEPLOYMENT_INSPECTOR_URL }'>${ steps.vercel-deploy.outputs.DEPLOYMENT_INSPECTOR_URL }</a></td>
#              </tr>
#            </table>
#
#            [View Workflow Logs](${ LOG_URL })
#          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
#          COMMENT_IDENTIFIER: 'vercel-deploy'